name: "✨ Feature Request"
description: Suggest a feature or enhancement to improve the GEWIS website.
labels: ["Type: Idea"]
type: "Feature"
body:
    -   type: textarea
        id: feature
        attributes:
            label: What would you like?
            description: A clear description of the feature or enhancement wanted.
            placeholder: I'd like to be able to...
        validations:
            required: true
    -   type: textarea
        id: reason
        attributes:
            label: Why is this needed?
            description: A clear description of why this would be useful to have.
            placeholder: I want this because...
    -   type: input
        id: url
        attributes:
            label: Which page does this concern?
            description: Paste the full URL of the page this feature or enhancement relates to. Leave this empty if it does not apply.
            placeholder: ex. https://gewis.nl/en/association/committees
    -   type: textarea
        id: other
        attributes:
            label: Other information
            placeholder: Any other details?
